'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'English' | 'Indonesia';

const translations = {
  English: {
    language: 'Language',
    inputConfig: 'Input Configuration',
    generateBtn: 'Generate Result & Prompt',
    generating: 'Generating Strategy...',
    results: 'Generated Results',
    copyResult: 'Copy Result',
    copyPrompt: 'Copy Master Prompt',
    masterPrompt: 'Master Prompt',
    output: 'Generated Output',
    noPrompt: 'No prompt generated yet',
    configureMsg: 'Configure the inputs on the left and click generate to see the magic.',
    processing: 'AI is generating 30 high-quality content prompts. This may take up to 60 seconds. Please stay on this page...',
    aiAssistant: 'AI Assistant',
    systemStatus: 'System Status',
    online: 'All Systems Online',
    systemStatusTitle: 'System Status',
    dashboard: 'Dashboard',
    contentLab: 'Content Lab',
    imageStudio: 'Image Studio',
    videoFactory: 'Video Factory',
    voiceLab: 'Voice Lab',
    reverseEngineering: 'Reverse Engineering',
    automation: 'Automation',
    tool1Name: 'Content Strategy Suite',
    tool1Desc: 'Generate high-authority content prompts for any platform.',
    tool3Name: 'Text to Image',
    tool3Desc: 'Master-level prompts for Midjourney, DALL-E, and Stable Diffusion.',
    tool4Name: 'Image Editor',
    tool4Desc: 'Precise instructions for AI image editing and retouching.',
    tool5Name: 'Text to Video',
    tool5Desc: 'Cinematic scene descriptions for Sora, Runway, and Luma.',
    tool6Name: 'Content Generator (UGC)',
    tool6Desc: 'Generate high-quality UGC content with AI.',
    tool7Name: 'Cinematic AI Film',
    tool7Desc: 'Full production plan with scene-by-scene Shot List for AI films.',
    tool8Name: 'End-to-End Video Prompt',
    tool8Desc: 'The SUPER PROMPT for end-to-end video production.',
    tool10Name: 'Master Voice Generator',
    tool10Desc: 'Professional audio prompts for Suno, Udio, and ElevenLabs.',
    tool11Name: 'AI Voice / Narration',
    tool11Desc: 'Perfect scripts and direction for AI voiceovers.',
    tool12Name: 'Image to Prompt',
    tool12Desc: 'Reverse engineer any image into a professional prompt.',
    tool13Name: 'Video to Prompt',
    tool13Desc: 'Deconstruct video styles into text-to-video prompts.',
    heroBadge: 'Next-Gen AI Prompt Engineering',
    heroTitle: 'CRAFT THE <br /> FUTURE OF AI',
    heroDesc: 'Neura Generator Ai is the professional toolkit for prompt engineering. Generate hyper-optimized prompts for content, images, video, and automation.',
    getStarted: 'Get Started',
    feature1Title: 'Content Lab',
    feature1Desc: 'Professional suites for articles, social media, and SEO strategy.',
    feature2Title: 'Visual Studio',
    feature2Desc: 'Advanced prompt generators for high-end image and video production.',
    feature3Title: 'Automation',
    feature3Desc: 'Scale your content production with 1-click multi-platform factories.',
    stat1: 'Tools Available',
    stat2: 'Prompt Accuracy',
    stat3: 'Processing Speed',
    stat4: 'AI Models',
    aiAssistantDesc: 'Chat with our most advanced AI model for brainstorming, coding, and creative writing.',
    launchAssistant: 'Launch Assistant',
    futureOf: 'The Future of',
    creativeIntelligence: 'Creative Intelligence.',
    toolNotFound: 'Tool not found',
    neuraTool: 'Neura Generator Ai Tool',
    allInOneContent: 'All-in-one content creation',
    advancedAIReasoning: 'Advanced AI reasoning',
    viralShortVideo: 'Viral short-form video',
    workflowAutomation: 'Workflow automation',
    aiImageGeneration: 'AI image generation',
    professionalAIEditing: 'Professional AI editing',
    cinematicAIVideo: 'Cinematic AI video',
    fullLengthFilm: 'Full-length film production',
    endToEndVideo: 'End-to-end video suite',
    aiSoundEffects: 'AI sound effects',
    naturalVoiceCloning: 'Natural voice cloning',
    deconstructAIImages: 'Deconstruct AI images',
    analyzeAIVideos: 'Analyze AI videos',
    // Tool Fields
    contentType: 'Content Type',
    objective: 'Objective',
    toneStyle: 'Tone Style',
    targetAudience: 'Target Audience',
    mainProblemSolved: 'Main Problem Solved',
    mention: 'Mention',
    hashtag: 'Hashtag',
    mainTopic: 'Main Topic',
    outputFormat: 'Output Format',
    imageCategory: 'Image Category',
    visualStyle: 'Visual Style',
    composition: 'Composition',
    cameraLanguage: 'Camera Language',
    lightingDesign: 'Lighting Design',
    colorDesign: 'Color Design',
    moodStory: 'Mood & Story',
    subject: 'Subject',
    videoGenre: 'Video Genre',
    cameraMotion: 'Camera Motion',
    sceneDescription: 'Scene Description',
    keywordsTopic: 'Keywords / Topic',
    specificGoal: 'Specific Goal (Optional)',
    targetAIPlatform: 'Target AI Platform',
    nicheCategory: 'Niche / Category',
    platformTarget: 'Platform Target',
    contentGoal: 'Content Goal',
    uploadImage: 'Upload Image',
    editMode: 'Edit Mode',
    styleControl: 'Style Control (Optional)',
    lightingAdjustment: 'Lighting Adjustment',
    gradingAdjustment: 'Color Adjustment',
    cameraPosition: 'Camera Position',
    editInstruction: 'Edit Instruction',
    productPhoto: 'Upload Product Photo (3:4)',
    modelFacePhoto: 'Upload Model/Face Photo (3:4)',
    productName: 'Product Name',
    backgroundSetting: 'Background Setting',
    toneVoice: 'Tone / Style',
    filmTitle: 'Film Title',
    coreConcept: 'Core Idea / Concept',
    shotCount: 'Number of Shots (Optional)',
    characterDetails: 'Character Details (Optional)',
    environmentDetails: 'Environment (Optional)',
    genre: 'Genre',
    mood: 'Mood',
    soundDetails: 'Sound Details',
    gender: 'Gender',
    emotion: 'Emotion',
    accent: 'Accent',
    scriptTopic: 'Script/Topic',
    videoTopic: 'Video Topic',
    imageUrl: 'Image URL (Optional)',
    visualDescription: 'Visual Description',
    videoSceneDescription: 'Video Scene Description',
    additionalInstructions: 'Additional Instructions (Optional)',
    additionalInstructionsPlaceholder: 'e.g. Use bullet points, include a call to action, etc.',
    // New Text to Video Fields
    genreVideo: 'Video Genre',
    cameraMovement: 'Camera Movement',
    aspectRatio: 'Aspect Ratio',
    cameraFocus: 'Camera Focus',
    emotionalFocus: 'Emotional Focus',
    lighting: 'Lighting',
    textureRealism: 'Texture & Realism',
    weatherVariation: 'Weather Variation',
    videoDuration: 'Video Duration',
    soundDesign: 'Sound Design',
    // Roles
    cinematographyRole: 'Cinematography Role',
    modernContentRole: 'Modern Content Role',
    artisticRole: 'Artistic Role',
    // Options
    genreVideoOptions: ['Cinematic Movie Scene', 'Documentary Realism', 'Action Thriller', 'Romantic Drama', 'Horror Atmosphere', 'Sci-Fi Futuristic', 'Fantasy Epic', 'Slice of Life Realistic', 'Travel Vlog Style', 'Cyberpunk Neo City', 'Historical Period Drama', 'Comedy Light Tone', 'Mystery Investigation', 'Post-Apocalyptic Survival', 'Commercial Advertisement Style'],
    cameraMovementOptions: ['Static Tripod Shot', 'Slow Cinematic Dolly In', 'Dolly Out Reveal Shot', 'Handheld Realistic Camera', 'Smooth Tracking Shot', 'Drone Aerial Flyover', 'Orbit Camera Movement', 'Over-the-Shoulder Follow Shot', 'Slow Push-In Emotional Shot', 'Cinematic Crane Shot'],
    aspectRatioOptions: ['16:9 (YouTube / Standard Film)', '9:16 (Reels / TikTok / Shorts)', '1:1 (Instagram Square)', '2.39:1 (Ultra Cinematic Scope)', '4:3 (Vintage Film Look)', '3:2 (Photography Style)', '21:9 (Ultra Wide Cinema)'],
    cameraFocusOptions: ['Extreme Close Up', 'Close Up Portrait', 'Medium Shot', 'Full Body Shot', 'Wide Environmental Shot', 'Deep Focus Scene', 'Shallow Depth of Field (Bokeh)', 'Rack Focus Transition'],
    emotionalFocusOptions: ['Melancholic & Lonely', 'Hopeful & Inspiring', 'Tense & Suspenseful', 'Warm & Nostalgic', 'Romantic & Soft', 'Dark & Mysterious', 'Joyful & Energetic', 'Dramatic & Epic'],
    lightingOptions: ['Natural Soft Daylight', 'Golden Hour Sunset', 'Blue Hour Cinematic', 'Low Key Dramatic Lighting', 'High Key Bright Lighting', 'Neon Cyberpunk Lighting', 'Moody Shadow Lighting', 'Overcast Diffused Light'],
    textureRealismOptions: ['Shabby clothes, dust flying in the air', 'Wet streets, faint light reflections', 'Cracked walls and peeling paint', 'Thin smoke and visible air particles', 'Natural facial skin with clear pores', 'Mud, soil stains, and dirty shoes', 'Thin mist mixed with dim light', 'Crowded environment with untidy random objects'],
    weatherVariationOptions: ['Sunny Clear Sky', 'Light Rain Drizzle', 'Heavy Rain Storm', 'Foggy Morning', 'Cloudy Overcast', 'Golden Sunset Weather', 'Windy Atmosphere', 'Thunderstorm Lightning', 'Snowfall Soft', 'Humid Tropical Heat'],
    videoDurationOptions: ['5s', '8s', '10s', '12s', '15s', '20s', '25s', '30s'],
    soundDesignOptions: ['Ambient city noise', 'Quiet cinematic room tone', 'Wind blowing atmosphere', 'Rain ambience', 'Thunderstorm environment', 'Forest nature ambience', 'Ocean waves sound', 'Busy street market sound', 'Footsteps and fabric movement', 'Distant traffic ambience', 'Industrial mechanical background', 'Night ambience insects', 'Fire crackling sound', 'Crowd murmur atmosphere', 'Urban neon nightlife ambience'],
    cinematographyRoles: ['Professional Film Director', 'Hollywood Cinematographer', 'Indie Film Creator', 'Documentary Filmmaker', 'Award-Winning Movie Director'],
    modernContentRoles: ['Viral TikTok Creator', 'Travel Vlogger', 'YouTube Documentary Creator', 'Lifestyle Content Creator', 'Social Media Storyteller'],
    artisticRoles: ['Visual Story Artist', 'Experimental Film Artist', 'Fashion Film Director', 'Music Video Director', 'Cinematic Photographer'],
    label_original: 'Original Image',
    placeholder_original: 'No image uploaded yet',
    label_result: 'AI Edited Result',
    placeholder_result: 'Edited image will appear here',
    loading_msg: 'AI is processing your image...',
    btn_download: 'Download Result',
    error_msg: 'Failed to process image. Please try again.',
    placeholder_instructions: 'Describe what you want to change (e.g., "Change the background to a sunset beach", "Make the lighting warmer")',
    btn_processing: 'Applying Changes...',
    btn_apply: 'Apply AI Edit',
    chat_welcome: 'Hello! I am your Neura Generator Ai AI Assistant. How can I help you with your prompt engineering today?',
    chat_error: 'Sorry, I encountered an error.',
    chat_quota_error: 'Error: API Quota Exceeded. You have reached the rate limit for the Groq API. Please wait a moment.',
    chat_connection_error: 'Error: Could not connect to the AI service. All fallback models and keys are exhausted.',
    chat_title: 'AI Assistant',
    chat_subtitle: 'Expert guidance for your creative workflow.',
    chat_cleared: 'Chat cleared. How can I help you?',
    chat_you: 'You',
    chat_assistant: 'Assistant',
    chat_thinking: 'Thinking...',
    chat_placeholder: 'Ask anything...',
    proMode: 'Pro Mode',
    clickToUpload: 'Click to upload',
    uploadLimits: 'PNG, JPG or WEBP (MAX. 5MB)',
    selectPlaceholder: 'Select {field}...',
    quotaTitle: 'API Quota Exceeded',
    quotaDesc: 'You have reached the rate limit for the Groq API. To continue using the app without interruptions, please wait or check your API configuration.',
    selectKeyBtn: 'Select My API Key',
    learnBillingBtn: 'Learn about Billing',
    copiedBtn: 'Copied!',
    copyAllBtn: 'Copy All Results',
    copyStrategyBtn: 'Copy Strategy',
    nanoBanana: '(Llama 3.3 70B)',
    llamaModel: '(Llama 3.3 70B)',
    downloadImageBtn: 'Download Image',
    copySpecificBtn: 'Copy {title}',
    videoPromptError: 'An error occurred while generating the video prompt.',
    uploadProductError: 'Please upload a product photo first.',
    descriptionRequiredError: 'Processing failed. Make sure the product description is filled in.',
    reviewModel: 'Review Model',
    productPOV: 'Product POV',
    productReference: 'Product Reference',
    uploadProduct: 'Upload Product',
    modelIdentity: 'Model Identity',
    uploadFace: 'Upload Face',
    referenceImage: 'Reference Image',
    uploadReference: 'Upload Reference',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Example: 24-hour matte lipstick, doesn\'t dry out lips, rose nude color...',
    generateContentBtn: 'GENERATE CONTENT',
    backBtn: 'Back',
    storyboardModeDesc: 'Storyboard Mode: 3 Frames Locked for Video Scene',
    ugcModeDesc: 'UGC Mode: Click image for AI Video Prompt',
    aiVideoPromptEngine: 'AI Video Prompt Engine',
    visualStyleLabel: 'Visual Style',
    atmosphereLabel: 'Atmosphere',
    cameraMotionLabel: 'Camera Motion',
    lightingLabel: 'Lighting',
    soundMusicLabel: 'Sound & Music',
    spokenLinesLabel: 'Spoken Lines',
    spokenLinesPlaceholder: 'Type the lines spoken by the model...',
    generateStoryPromptBtn: 'GENERATE STORY VIDEO PROMPT',
    generateMotionPromptBtn: 'GENERATE MOTION PROMPT',
    promptCopied: 'PROMPT COPIED',
    copyFullPrompt: 'COPY FULL PROMPT',
    captionLabel: 'Caption',
    copiedLabel: 'COPIED',
    copyCaptionBtn: 'COPY CAPTION',
    smartHashtagsLabel: 'Smart Hashtags',
    synergizingAssets: 'Synergizing Assets',
    synergizingMessage: 'AI is synergizing {feature} visuals with your chosen background.',
    selectApiKeyBtn: 'Select API Key',
    // Content Suite Options
    contentSuiteTypes: ['Article Professional', 'Twitter/X Engagement Post', 'LinkedIn Authority Post', 'Marketing Campaign', 'Project Feedback Report', 'Product Launch Content', 'Brand Storytelling', 'SEO Blog'],
    contentSuiteObjectives: ['Authority Building', 'Lead Generation', 'Sales Conversion', 'Education', 'Community Growth', 'Brand Awareness', 'Viral Engagement', 'Answers', 'Analysis', 'Reasoning', 'Vision & Mission', 'Conclusion', 'Summary'],
    contentSuiteTones: ['Professional', 'Persuasive', 'Minimalist', 'Storytelling', 'Technical Expert', 'Emotional', 'Premium Luxury'],
    contentSuiteAudiences: ['Startup Founder', 'Creator Economy', 'Corporate', 'AI Enthusiast', 'Developer', 'General Audience'],
    contentSuiteOutputs: ['1 tweet 240-280 Character', '1 tweet 250-400 Character', 'Step by step Tutorial', '1 Caption Social Media', 'Article paragraph', 'None'],
    // Text to Image Options
    imageCategories: ['cinematic scene', 'portrait', 'product photography', 'concept art', 'illustration', 'fashion editorial', 'architecture', 'fantasy artwork', 'sci-fi environment', 'advertising visual', 'social media artwork', 'UI design', 'logo concept'],
    visualStyles: ['photorealistic', 'hyperrealistic', 'anime style', 'oil painting', 'watercolor', 'digital illustration', 'cinematic realism', '3D render', 'cyberpunk', 'minimalist design'],
    compositions: ['rule of thirds', 'centered composition', 'cinematic framing', 'minimal composition', 'dynamic perspective'],
    cameraLanguages: ['wide shot', 'close-up', 'macro shot', 'low angle', 'high angle', 'drone view', 'portrait lens', 'depth of field', 'bokeh background'],
    lightingDesigns: ['soft natural light', 'studio lighting', 'cinematic lighting', 'golden hour', 'neon light', 'dramatic shadows', 'rim light', 'volumetric light'],
    colorDesigns: ['warm tone', 'pastel palette', 'vibrant colors', 'monochrome', 'teal & orange cinematic', 'moody contrast'],
    moodStories: ['Epic', 'Emotional', 'Dark', 'Futuristic', 'Peaceful', 'Luxury', 'Mysterious', 'Action-packed'],
    // Text to Video Options
    videoGenres: ['Cinematic Film', 'Documentary', 'Commercial Ads', 'Music Video', 'Travel Film', 'Product Promo', 'Anime Scene', 'Sci-Fi Trailer', 'Luxury Brand Video', 'YouTube Video', 'Viral Shorts'],
    cameraMotions: ['Static', 'Pan Left/Right', 'Tilt Up/Down', 'Zoom In/Out', 'Drone Orbit', 'Handheld Shake', 'Tracking Shot'],
    // Meta LLM Options
    aiPlatforms: ['Universal', 'ChatGPT', 'Claude', 'Groq', 'Midjourney', 'Stable Diffusion'],
    // Automation Factory Options
    nicheCategories: ['Technology', 'Health & Wellness', 'Business & Finance', 'Lifestyle', 'Education', 'Entertainment', 'Real Estate', 'SaaS & Startups'],
    platformTargets: ['Instagram', 'LinkedIn', 'TikTok', 'Twitter/X', 'YouTube', 'Multi-Platform'],
    contentGoals: ['Sales / Jualan', 'Personal Branding', 'Education / Edukasi', 'Lead Generation', 'Viral Growth'],
    // Image Editor Options
    editModes: ['enhancement', 'inpainting', 'outpainting', 'relighting', 'recolor', 'retouch', 'style transfer', 'object replace'],
    styleControls: ['photorealistic', 'cinematic', 'fashion editorial', 'anime style', 'luxury commercial'],
    lightingAdjustments: ['exposure correction', 'cinematic lighting', 'shadow balance'],
    gradingAdjustments: ['color grading', 'tone adjustment', 'white balance'],
    cameraPositions: ['Eye Level', 'Low Angle', 'High Angle', 'Bird\'s Eye View', 'Worm\'s Eye View', 'Dutch Angle', 'Over the Shoulder', 'Close Up', 'Wide Shot', 'Macro'],
    // Shorts Factory Options
    backgroundSettings: ['Modern Bedroom', 'Minimalist Studio', 'Outdoor Park', 'Luxury Living Room', 'Professional Office', 'Cozy Cafe', 'Nature/Forest', 'Futuristic Lab'],
    toneVoices: ['Energetic & Hype', 'Professional & Trustworthy', 'Soft & Calm', 'Funny & Relatable', 'Luxury & Elegant', 'Educational & Clear'],
    // Film Generator Options
    filmGenres: ['cinematic drama', 'sci-fi', 'documentary', 'thriller', 'luxury commercial', 'cyberpunk', 'fantasy', 'inspirational', 'noir', 'emotional storytelling'],
    // Sound Generator Options
    soundGenres: ['Cinematic', 'Ambient', 'EDM', 'Lo-Fi', 'Epic Orchestra', 'Horror Atmosphere', 'Meditation', 'Podcast Background'],
    soundMoods: ['Happy', 'Sad', 'Aggressive', 'Calm', 'Mysterious', 'Energetic'],
    // Voice Generator Options
    genders: ['Male', 'Female', 'Non-binary', 'Neutral'],
    emotions: ['Professional', 'Excited', 'Serious', 'Whispering', 'Storyteller', 'Angry'],
    accents: ['US English', 'UK English', 'Australian', 'Indian', 'European'],
  },
  Indonesia: {
    language: 'Bahasa',
    inputConfig: 'Konfigurasi Input',
    generateBtn: 'Hasilkan Hasil & Prompt',
    generating: 'Menghasilkan Strategi...',
    results: 'Hasil yang Dihasilkan',
    copyResult: 'Salin Hasil',
    copyPrompt: 'Salin Master Prompt',
    masterPrompt: 'Master Prompt',
    output: 'Output yang Dihasilkan',
    noPrompt: 'Belum ada prompt yang dihasilkan',
    configureMsg: 'Konfigurasikan input di sebelah kiri dan klik hasilkan untuk melihat keajaiban.',
    processing: 'AI sedang menghasilkan 30 prompt konten berkualitas tinggi. Ini mungkin memakan waktu hingga 60 detik. Harap tetap di halaman ini...',
    aiAssistant: 'Asisten Ai',
    systemStatus: 'Status Sistem',
    online: 'Semua Sistem Online',
    systemStatusTitle: 'Status Sistem',
    dashboard: 'Dashboard',
    contentLab: 'Lab Konten',
    imageStudio: 'Image Studio',
    videoFactory: 'Video Studio',
    voiceLab: 'Lab Suara dan Bunyi',
    reverseEngineering: 'Rekayasa Balik',
    automation: 'Otomatisasi',
    tool1Name: 'Strategi Penulisan',
    tool1Desc: 'Hasilkan prompt konten otoritas tinggi untuk platform apa pun.',
    tool3Name: 'Teks ke Gambar',
    tool3Desc: 'Prompt tingkat master untuk Midjourney, DALL-E, dan Stable Diffusion.',
    tool4Name: 'Editor Gambar',
    tool4Desc: 'Instruksi presisi untuk pengeditan dan retouching gambar AI.',
    tool5Name: 'Teks ke Video',
    tool5Desc: 'Deskripsi adegan sinematik untuk Sora, Runway, dan Luma.',
    tool6Name: 'Generator Konten (UGC)',
    tool6Desc: 'Hasilkan konten UGC berkualitas tinggi dengan AI.',
    tool7Name: 'Film AI Sinematik',
    tool7Desc: 'Rencana produksi lengkap dengan Shot List adegan-per-adegan untuk film AI.',
    tool8Name: 'Prompt Video Lengkap',
    tool8Desc: 'SUPER PROMPT untuk produksi video end-to-end.',
    tool10Name: 'Generator Suara Master',
    tool10Desc: 'Prompt audio profesional untuk Suno, Udio, dan ElevenLabs.',
    tool11Name: 'Suara / Narasi AI',
    tool11Desc: 'Skrip dan arahan sempurna untuk voiceover AI.',
    tool12Name: 'Gambar ke Prompt',
    tool12Desc: 'Rekayasa balik gambar apa pun menjadi prompt profesional.',
    tool13Name: 'Video ke Prompt',
    tool13Desc: 'Dekonstruksi gaya video menjadi prompt teks-ke-video.',
    heroBadge: 'Prompt Engineering Generasi Berikutnya',
    heroTitle: 'BANGUN <br /> MASA DEPAN AI',
    heroDesc: 'Neura Generator Ai adalah toolkit profesional untuk prompt engineering. Hasilkan prompt yang sangat dioptimalkan untuk konten, gambar, video, dan otomatisasi.',
    getStarted: 'Mulai Sekarang',
    feature1Title: 'Lab Konten',
    feature1Desc: 'Suite profesional untuk artikel, media sosial, dan strategi SEO.',
    feature2Title: 'Studio Visual',
    feature2Desc: 'Generator prompt canggih untuk produksi gambar dan video kelas atas.',
    feature3Title: 'Otomatisasi',
    feature3Desc: 'Skalakan produksi konten Anda dengan pabrik multi-platform 1-klik.',
    stat1: 'Alat Tersedia',
    stat2: 'Akurasi Prompt',
    stat3: 'Kecepatan Proses',
    stat4: 'Model AI',
    aiAssistantDesc: 'Ngobrol dengan model AI tercanggih kami untuk brainstorming, coding, dan penulisan kreatif.',
    launchAssistant: 'Luncurkan Asisten',
    futureOf: 'Masa Depan',
    creativeIntelligence: 'Kecerdasan Kreatif.',
    toolNotFound: 'Alat tidak ditemukan',
    neuraTool: 'Alat Neura Generator Ai',
    allInOneContent: 'Pembuatan konten lengkap',
    advancedAIReasoning: 'Penalaran AI tingkat lanjut',
    viralShortVideo: 'Video pendek viral',
    workflowAutomation: 'Otomatisasi alur kerja',
    aiImageGeneration: 'Pembuatan gambar AI',
    professionalAIEditing: 'Pengeditan AI profesional',
    cinematicAIVideo: 'Video AI sinematik',
    fullLengthFilm: 'Produksi film panjang',
    endToEndVideo: 'Suite video lengkap',
    aiSoundEffects: 'Efek suara AI',
    naturalVoiceCloning: 'Kloning suara alami',
    deconstructAIImages: 'Dekonstruksi gambar AI',
    analyzeAIVideos: 'Analisis video AI',
    // Tool Fields
    contentType: 'Tipe Konten',
    objective: 'Tujuan',
    toneStyle: 'Gaya Nada',
    targetAudience: 'Target Audiens',
    mainProblemSolved: 'Masalah Utama yang Dipecahkan',
    mention: 'Sebutan (Mention)',
    hashtag: 'Tagar (Hashtag)',
    mainTopic: 'Topik Utama',
    outputFormat: 'Format Output',
    imageCategory: 'Kategori Gambar',
    visualStyle: 'Gaya Visual',
    composition: 'Komposisi',
    cameraLanguage: 'Bahasa Kamera',
    lightingDesign: 'Desain Pencahayaan',
    colorDesign: 'Desain Warna',
    moodStory: 'Suasana & Cerita',
    subject: 'Subjek',
    videoGenre: 'Genre Video',
    cameraMotion: 'Gerakan Kamera',
    sceneDescription: 'Deskripsi Adegan',
    keywordsTopic: 'Kata Kunci / Topik',
    specificGoal: 'Tujuan Spesifik (Opsional)',
    targetAIPlatform: 'Target Platform AI',
    nicheCategory: 'Niche / Kategori',
    platformTarget: 'Target Platform',
    contentGoal: 'Tujuan Konten',
    uploadImage: 'Unggah Gambar',
    editMode: 'Mode Edit',
    styleControl: 'Kontrol Gaya (Opsional)',
    lightingAdjustment: 'Penyesuaian Cahaya',
    gradingAdjustment: 'Penyesuaian Warna',
    cameraPosition: 'Posisi Kamera',
    editInstruction: 'Instruksi Edit',
    productPhoto: 'Unggah Foto Produk (3:4)',
    modelFacePhoto: 'Unggah Foto Model/Wajah (3:4)',
    productName: 'Nama Produk',
    backgroundSetting: 'Pengaturan Latar Belakang',
    toneVoice: 'Nada / Gaya Bahasa',
    filmTitle: 'Judul Film',
    coreConcept: 'Ide Inti / Konsep',
    shotCount: 'Jumlah Shot (Opsional)',
    characterDetails: 'Detail Karakter (Opsional)',
    environmentDetails: 'Lingkungan (Opsional)',
    genre: 'Genre',
    mood: 'Suasana',
    soundDetails: 'Detail Suara',
    gender: 'Jenis Kelamin',
    emotion: 'Emosi',
    accent: 'Aksen',
    scriptTopic: 'Skrip/Topik',
    videoTopic: 'Topik Video',
    imageUrl: 'URL Gambar (Opsional)',
    visualDescription: 'Deskripsi Visual',
    videoSceneDescription: 'Deskripsi Adegan Video',
    additionalInstructions: 'Perintah Tambahan (Opsional)',
    additionalInstructionsPlaceholder: 'Misal: Gunakan poin-poin, sertakan ajakan bertindak, dll.',
    // New Text to Video Fields
    genreVideo: 'Genre Video',
    cameraMovement: 'Gerakan Kamera',
    aspectRatio: 'Rasio Aspek',
    cameraFocus: 'Fokus Kamera',
    emotionalFocus: 'Fokus Emosi',
    lighting: 'Pencahayaan',
    textureRealism: 'Detail Tekstur Realisme',
    weatherVariation: 'Variasi Cuaca',
    videoDuration: 'Durasi Video',
    soundDesign: 'Sound Design',
    // Roles
    cinematographyRole: 'Role Sinematografi',
    modernContentRole: 'Role Konten Modern',
    artisticRole: 'Role Artistik',
    // Options
    genreVideoOptions: ['Cinematic Movie Scene', 'Documentary Realism', 'Action Thriller', 'Romantic Drama', 'Horror Atmosphere', 'Sci-Fi Futuristic', 'Fantasy Epic', 'Slice of Life Realistic', 'Travel Vlog Style', 'Cyberpunk Neo City', 'Historical Period Drama', 'Comedy Light Tone', 'Mystery Investigation', 'Post-Apocalyptic Survival', 'Commercial Advertisement Style'],
    cameraMovementOptions: ['Static Tripod Shot', 'Slow Cinematic Dolly In', 'Dolly Out Reveal Shot', 'Handheld Realistic Camera', 'Smooth Tracking Shot', 'Drone Aerial Flyover', 'Orbit Camera Movement', 'Over-the-Shoulder Follow Shot', 'Slow Push-In Emotional Shot', 'Cinematic Crane Shot'],
    aspectRatioOptions: ['16:9 (YouTube / Film Standar)', '9:16 (Reels / TikTok / Shorts)', '1:1 (Instagram Square)', '2.39:1 (Ultra Cinematic Scope)', '4:3 (Vintage Film Look)', '3:2 (Photography Style)', '21:9 (Ultra Wide Cinema)'],
    cameraFocusOptions: ['Extreme Close Up', 'Close Up Portrait', 'Medium Shot', 'Full Body Shot', 'Wide Environmental Shot', 'Deep Focus Scene', 'Shallow Depth of Field (Bokeh)', 'Rack Focus Transition'],
    emotionalFocusOptions: ['Melancholic & Lonely', 'Hopeful & Inspiring', 'Tense & Suspenseful', 'Warm & Nostalgic', 'Romantic & Soft', 'Dark & Mysterious', 'Joyful & Energetic', 'Dramatic & Epic'],
    lightingOptions: ['Natural Soft Daylight', 'Golden Hour Sunset', 'Blue Hour Cinematic', 'Low Key Dramatic Lighting', 'High Key Bright Lighting', 'Neon Cyberpunk Lighting', 'Moody Shadow Lighting', 'Overcast Diffused Light'],
    textureRealismOptions: ['Pakaian lusuh, debu beterbangan di udara', 'Jalanan basah, pantulan cahaya samar', 'Tembok retak dan cat mengelupas', 'Asap tipis dan partikel udara terlihat', 'Kulit wajah natural dengan pori-pori jelas', 'Lumpur, noda tanah, dan sepatu kotor', 'Kabut tipis bercampur cahaya redup', 'Lingkungan ramai dengan objek acak tidak rapi'],
    weatherVariationOptions: ['Sunny Clear Sky', 'Light Rain Drizzle', 'Heavy Rain Storm', 'Foggy Morning', 'Cloudy Overcast', 'Golden Sunset Weather', 'Windy Atmosphere', 'Thunderstorm Lightning', 'Snowfall Soft', 'Humid Tropical Heat'],
    videoDurationOptions: ['5s', '8s', '10s', '12s', '15s', '20s', '25s', '30s'],
    soundDesignOptions: ['Ambient city noise — suara kota jauh, kendaraan samar, kehidupan urban', 'Quiet cinematic room tone — keheningan alami dengan ambience halus', 'Wind blowing atmosphere — angin lembut atau angin kuat melewati lingkungan', 'Rain ambience — tetesan hujan mengenai tanah, atap, dan objek sekitar', 'Thunderstorm environment — hujan deras dengan petir dan gemuruh langit', 'Forest nature ambience — burung, serangga, daun bergerak alami', 'Ocean waves sound — ombak pantai dan hembusan angin laut', 'Busy street market sound — keramaian manusia, suara aktivitas sosial', 'Footsteps and fabric movement — langkah kaki dan gesekan pakaian realistis', 'Distant traffic ambience — kendaraan jauh tanpa dominasi suara mesin', 'Industrial mechanical background — mesin, logam, dan suara pabrik samar', 'Night ambience insects — jangkrik malam dan suasana sunyi malam hari', 'Fire crackling sound — api kecil menyala dan kayu terbakar', 'Crowd murmur atmosphere — percakapan ramai tapi tidak fokus pada dialog', 'Urban neon nightlife ambience — dengung listrik, kota malam, energi modern'],
    cinematographyRoles: ['Professional Film Director', 'Hollywood Cinematographer', 'Indie Film Creator', 'Documentary Filmmaker', 'Award-Winning Movie Director'],
    modernContentRoles: ['Viral TikTok Creator', 'Travel Vlogger', 'YouTube Documentary Creator', 'Lifestyle Content Creator', 'Social Media Storyteller'],
    artisticRoles: ['Visual Story Artist', 'Experimental Film Artist', 'Fashion Film Director', 'Music Video Director', 'Cinematic Photographer'],
    label_original: 'Gambar Asli',
    placeholder_original: 'Belum ada gambar yang diunggah',
    label_result: 'Hasil Edit AI',
    placeholder_result: 'Gambar hasil edit akan muncul di sini',
    loading_msg: 'AI sedang memproses gambar Anda...',
    btn_download: 'Unduh Hasil',
    error_msg: 'Gagal memproses gambar. Silakan coba lagi.',
    placeholder_instructions: 'Jelaskan apa yang ingin Anda ubah (misal: "Ubah latar belakang menjadi pantai saat matahari terbenam", "Buat pencahayaan lebih hangat")',
    btn_processing: 'Menerapkan Perubahan...',
    btn_apply: 'Terapkan Edit AI',
    chat_welcome: 'Halo! Saya Asisten AI Neura Generator Ai. Bagaimana saya bisa membantu Anda dengan prompt engineering hari ini?',
    chat_error: 'Maaf, saya mengalami kesalahan.',
    chat_quota_error: 'Kesalahan: Kuota API Terlampaui. Anda telah mencapai batas kecepatan untuk API Groq. Harap tunggu sebentar.',
    chat_connection_error: 'Kesalahan: Tidak dapat terhubung ke layanan AI. Semua model cadangan dan kunci telah habis.',
    chat_title: 'Asisten AI',
    chat_subtitle: 'Panduan ahli untuk alur kerja kreatif Anda.',
    chat_cleared: 'Obrolan dihapus. Ada yang bisa saya bantu?',
    chat_you: 'Anda',
    chat_assistant: 'Asisten',
    chat_thinking: 'Sedang berpikir...',
    chat_placeholder: 'Tanya apa saja...',
    proMode: 'Mode Pro',
    clickToUpload: 'Klik untuk unggah',
    uploadLimits: 'PNG, JPG atau WEBP (MAKS. 5MB)',
    selectPlaceholder: 'Pilih {field}...',
    quotaTitle: 'Kuota API Terlampaui',
    quotaDesc: 'Anda telah mencapai batas kecepatan untuk API Groq. Untuk melanjutkan penggunaan aplikasi tanpa gangguan, harap tunggu atau periksa konfigurasi API Anda.',
    selectKeyBtn: 'Pilih Kunci API Saya',
    learnBillingBtn: 'Pelajari tentang Penagihan',
    copiedBtn: 'Tersalin!',
    copyAllBtn: 'Salin Semua Hasil',
    copyStrategyBtn: 'Salin Strategi',
    nanoBanana: '(Llama 3.3 70B)',
    llamaModel: '(Llama 3.3 70B)',
    downloadImageBtn: 'Unduh Gambar',
    copySpecificBtn: 'Salin {title}',
    videoPromptError: 'Terjadi kesalahan saat menghasilkan prompt video.',
    uploadProductError: 'Silakan unggah foto produk terlebih dahulu.',
    descriptionRequiredError: 'Gagal memproses. Pastikan deskripsi produk sudah diisi.',
    reviewModel: 'Review Model',
    productPOV: 'POV Produk',
    productReference: 'Referensi Produk',
    uploadProduct: 'Unggah Produk',
    modelIdentity: 'Identitas Model',
    uploadFace: 'Unggah Wajah',
    referenceImage: 'Gambar Referensi',
    uploadReference: 'Unggah Referensi',
    descriptionLabel: 'Deskripsi',
    descriptionPlaceholder: 'Misal: Lipstik matte tahan 24 jam, tidak membuat bibir kering, warna rose nude...',
    generateContentBtn: 'HASILKAN KONTEN',
    backBtn: 'Kembali',
    storyboardModeDesc: 'Mode Storyboard: 3 Frame Terkunci untuk Adegan Video',
    ugcModeDesc: 'Mode UGC: Klik gambar untuk AI Video Prompt',
    aiVideoPromptEngine: 'Mesin Prompt Video AI',
    visualStyleLabel: 'Gaya Visual',
    atmosphereLabel: 'Atmosfer',
    cameraMotionLabel: 'Gerakan Kamera',
    lightingLabel: 'Pencahayaan',
    soundMusicLabel: 'Suara & Musik',
    spokenLinesLabel: 'Kalimat Ucapan',
    spokenLinesPlaceholder: 'Ketik kalimat yang diucapkan model...',
    generateStoryPromptBtn: 'HASILKAN PROMPT VIDEO CERITA',
    generateMotionPromptBtn: 'HASILKAN PROMPT GERAKAN',
    promptCopied: 'PROMPT TERSALIN',
    copyFullPrompt: 'SALIN SEMUA PROMPT',
    captionLabel: 'Keterangan',
    copiedLabel: 'TERSALIN',
    copyCaptionBtn: 'SALIN CAPTION',
    smartHashtagsLabel: 'Tagar Pintar',
    synergizingAssets: 'Menyinkronkan Aset',
    synergizingMessage: 'AI sedang menyinkronkan visual {feature} dengan latar belakang pilihan Anda.',
    selectApiKeyBtn: 'Pilih Kunci API',
    // Content Suite Options
    contentSuiteTypes: ['Artikel Profesional', 'Postingan Interaksi Twitter/X', 'Postingan Otoritas LinkedIn', 'Kampanye Pemasaran', 'Laporan Umpan Balik Proyek', 'Konten Peluncuran Produk', 'Storytelling Brand', 'Blog SEO'],
    contentSuiteObjectives: ['Membangun Otoritas', 'Lead Generation', 'Konversi Penjualan', 'Edukasi', 'Pertumbuhan Komunitas', 'Kesadaran Brand', 'Interaksi Viral', 'Jawaban', 'Analisa', 'Alasan', 'Visi & Misi', 'Kesimpulan', 'Ringkasan'],
    contentSuiteTones: ['Profesional', 'Persuasif', 'Minimalis', 'Storytelling', 'Pakar Teknis', 'Emosional', 'Mewah Premium'],
    contentSuiteAudiences: ['Pendiri Startup', 'Ekonomi Kreator', 'Korporat', 'Penggemar AI', 'Pengembang', 'Audiens Umum'],
    contentSuiteOutputs: ['1 tweet 240-280 Karakter', '1 tweet 250-400 Karakter', 'Tutorial Langkah demi Langkah', '1 Keterangan Media Sosial', 'Paragraf Artikel', 'Tidak Ada'],
    // Text to Image Options
    imageCategories: ['adegan sinematik', 'potret', 'fotografi produk', 'seni konsep', 'ilustrasi', 'editorial fashion', 'arsitektur', 'karya seni fantasi', 'lingkungan sci-fi', 'visual iklan', 'karya seni media sosial', 'desain UI', 'konsep logo'],
    visualStyles: ['fotorealistik', 'hiperrealistik', 'gaya anime', 'lukisan cat minyak', 'cat air', 'ilustrasi digital', 'realisme sinematik', 'render 3D', 'cyberpunk', 'desain minimalis'],
    compositions: ['aturan sepertiga', 'komposisi terpusat', 'pembingkaian sinematik', 'komposisi minimal', 'perspektif dinamis'],
    cameraLanguages: ['bidikan lebar', 'close-up', 'bidikan makro', 'sudut rendah', 'sudut tinggi', 'tampilan drone', 'lensa potret', 'kedalaman bidang', 'latar belakang bokeh'],
    lightingDesigns: ['cahaya alami lembut', 'pencahayaan studio', 'pencahayaan sinematik', 'golden hour', 'lampu neon', 'bayangan dramatis', 'rim light', 'volumetric light'],
    colorDesigns: ['nada hangat', 'palet pastel', 'warna-warna cerah', 'monokrom', 'teal & orange sinematik', 'kontras moody'],
    moodStories: ['Epik', 'Emosional', 'Gelap', 'Futuristik', 'Damai', 'Mewah', 'Misterius', 'Penuh Aksi'],
    // Text to Video Options
    videoGenres: ['Film Sinematik', 'Dokumenter', 'Iklan Komersial', 'Video Musik', 'Film Perjalanan', 'Promo Produk', 'Adegan Anime', 'Trailer Sci-Fi', 'Video Brand Mewah', 'Video YouTube', 'Shorts Viral'],
    cameraMotions: ['Statis', 'Geser Kiri/Kanan', 'Miring Atas/Bawah', 'Zoom In/Out', 'Orbit Drone', 'Guncangan Genggam', 'Bidikan Pelacakan'],
    // Meta LLM Options
    aiPlatforms: ['Universal', 'ChatGPT', 'Claude', 'Groq', 'Midjourney', 'Stable Diffusion'],
    // Automation Factory Options
    nicheCategories: ['Teknologi', 'Kesehatan & Kebugaran', 'Bisnis & Keuangan', 'Gaya Hidup', 'Edukasi', 'Hiburan', 'Real Estat', 'SaaS & Startup'],
    platformTargets: ['Instagram', 'LinkedIn', 'TikTok', 'Twitter/X', 'YouTube', 'Multi-Platform'],
    contentGoals: ['Penjualan / Jualan', 'Personal Branding', 'Edukasi / Education', 'Lead Generation', 'Pertumbuhan Viral'],
    // Image Editor Options
    editModes: ['peningkatan', 'inpainting', 'outpainting', 'pencahayaan ulang', 'pewarnaan ulang', 'retouch', 'transfer gaya', 'ganti objek'],
    styleControls: ['fotorealistik', 'sinematik', 'editorial fashion', 'gaya anime', 'komersial mewah'],
    lightingAdjustments: ['koreksi eksposur', 'pencahayaan sinematik', 'keseimbangan bayangan'],
    gradingAdjustments: ['grading warna', 'penyesuaian nada', 'keseimbangan putih'],
    cameraPositions: ['Eye Level', 'Low Angle', 'High Angle', 'Bird\'s Eye View', 'Worm\'s Eye View', 'Dutch Angle', 'Over the Shoulder', 'Close Up', 'Wide Shot', 'Macro'],
    // Shorts Factory Options
    backgroundSettings: ['Kamar Tidur Modern', 'Studio Minimalis', 'Taman Terbuka', 'Ruang Tamu Mewah', 'Kantor Profesional', 'Kafe Nyaman', 'Alam/Hutan', 'Lab Futuristik'],
    toneVoices: ['Energetik & Hype', 'Profesional & Terpercaya', 'Lembut & Tenang', 'Lucu & Relatable', 'Mewah & Elegan', 'Edukatif & Jelas'],
    // Film Generator Options
    filmGenres: ['drama sinematik', 'sci-fi', 'dokumenter', 'thriller', 'komersial mewah', 'cyberpunk', 'fantasi', 'inspirasional', 'noir', 'storytelling emosional'],
    // Sound Generator Options
    soundGenres: ['Sinematik', 'Ambient', 'EDM', 'Lo-Fi', 'Orkestra Epik', 'Atmosfer Horor', 'Meditasi', 'Latar Belakang Podcast'],
    soundMoods: ['Senang', 'Sedih', 'Agresif', 'Tenang', 'Misterius', 'Energetik'],
    // Voice Generator Options
    genders: ['Pria', 'Wanita', 'Non-biner', 'Netral'],
    emotions: ['Profesional', 'Bersemangat', 'Serius', 'Berbisik', 'Storyteller', 'Marah'],
    accents: ['Inggris AS', 'Inggris UK', 'Australia', 'India', 'Eropa'],
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations['English'];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [state, setState] = useState<{ lang: Language; mounted: boolean }>({
    lang: 'English',
    mounted: false,
  });

  useEffect(() => {
    const timer = setTimeout(() => {
      try {
        const savedLang = localStorage.getItem('neura-lang') as Language;
        const lang = (savedLang === 'English' || savedLang === 'Indonesia') ? savedLang : 'English';
        setState(prev => ({ ...prev, lang, mounted: true }));
      } catch (e) {
        console.error("Language initialization error:", e);
        setState(prev => ({ ...prev, mounted: true }));
      }
    }, 0);
    return () => clearTimeout(timer);
  }, []);

  const setLanguage = (lang: Language) => {
    try {
      setState(prev => ({ ...prev, lang }));
      localStorage.setItem('neura-lang', lang);
    } catch (e) {
      console.error("Failed to save language:", e);
    }
  };

  const t = translations[state.lang];

  return (
    <LanguageContext.Provider value={{ language: state.lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
